/* ─── REAL ROWS, ALONGSIDE THE BLOB ──────────────────────────────────────────
   App.jsx persists the whole workspace as two JSON strings in `app_kv`. That is
   fine for the app's own reads, but nothing else can ask a question of it: no
   "which projects are overdue", no join to an invoice, no per-row permissions,
   and — because it is one row — no way to hide anything from anyone.

   So every save also mirrors the workspace out to the real tables, one row per
   thing. The blob stays authoritative; this is a one-way mirror:

     App state ──► app_kv blob        (authoritative, unchanged)
               └─► projects, scrum_notes, tasks, clients, moms,
                   project_chat, project_intel, assistant_log,
                   kpi_log, work_updates, trainings, memory,
                   drive_sync_log     (a queryable copy)

   Nothing reads these rows back yet, which is exactly why it is safe to turn
   on: a failed write is invisible to the app and the next save repairs it.

   Run supabase/projects-into-a-real-table.sql and
       supabase/every-table-filled.sql
   first. Without them each write fails harmlessly and the tables stay empty.

   ── Two shape rules worth knowing ──
   • `app_id` is the app's own short id (`uid()`, 8 chars). It is the upsert
     key on every table, because the app's ids are not uuids and the uuid
     primary keys are generated by Postgres.
   • Columns declared `uuid references profiles(id)` only ever receive a real
     uuid. The seeded roster uses ids like 'u-admin', which would violate the
     foreign key and fail the entire batch, so those travel in the matching
     `*_app_id` text column instead.                                          */

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const isUuid = (v) => typeof v === "string" && UUID_RE.test(v);
/* Only a real uuid may enter a uuid column. */
const fk = (v) => (isUuid(v) ? v : null);

/* An empty date input is "", which Postgres rejects for a `date` column. */
const date = (v) => (typeof v === "string" && /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : null);
const text = (v) => (v == null || v === "" ? null : String(v));
const at = (v) => text(v) || new Date().toISOString();
const arr = (v) => (Array.isArray(v) ? v : []);
const obj = (v) => (v && typeof v === "object" && !Array.isArray(v) ? v : {});
const num = (v) => (Number.isFinite(Number(v)) ? Number(v) : null);

/* ── row builders ─────────────────────────────────────────────────────────── */

export function projectRow(p) {
  return {
    project_id: String(p.projectId || "").trim(),
    app_id: text(p.id),
    id_mode: text(p.idMode) || "auto",
    origin: text(p.origin),
    name: String(p.name || "").trim() || String(p.projectId || ""),
    description: text(p.description),
    client_name: text(p.clientName),
    client_id: text(p.clientId),
    industry: text(p.industry),
    org_size: text(p.orgSize),
    contact: obj(p.contact),
    start_date: date(p.startDate),
    deadline: date(p.deadline),
    status: text(p.status) || "Planning",
    linked_ids: arr(p.linkedIds).filter(Boolean).map(String),
    team: arr(p.team),
    known_status: text(p.knownStatus),
    drive_learning: text(p.driveLearning),
    lld_customer: p.lldCustomer ?? null,
    lld_designer: p.lldDesigner ?? null,
    created_by: fk(p.createdBy),
    created_at: at(p.createdAt),
  };
}

export const clientRow = (c) => ({
  app_id: text(c.id),
  client_id: text(c.clientId),
  name: String(c.name || "").trim() || "(unnamed)",
  industry: text(c.industry),
  org_size: text(c.orgSize),
});

/* The daily scrum. One row per note, so "what did we say on the 7th" is a
   query rather than a scan of a JSON string. */
export const scrumNoteRow = (n) => ({
  app_id: text(n.id),
  date: date(n.date),
  note_no: num(n.noteNo),
  time: text(n.time),
  raw: text(n.raw),
  organized: n.organized ?? null,
  origin: text(n.origin) || "manual",
  by: fk(n.by),
  by_app_id: text(n.by),
  project_id: text(n.projectId),
  created_at: at(n.createdAt),
});

export const taskRow = (t) => ({
  app_id: text(t.id),
  project_id: text(t.projectId),
  linked: t.linked !== false,
  title: String(t.title || "").trim() || "(untitled)",
  assignee_id: fk(t.assigneeId),
  assignee_app_id: text(t.assigneeId),
  assignee_name: text(t.assignee),
  date: date(t.date),
  start_time: text(t.startTime),
  end_time: text(t.endTime),
  steps: arr(t.steps),
  conditions: arr(t.conditions),
  // The column has a CHECK; an unknown status would fail the whole batch.
  status: ["pending", "in-progress", "blocked", "done"].includes(t.status) ? t.status : "pending",
  origin: text(t.origin) || "scrum",
  stage_id: text(t.stageId),
  note_app_id: text(t.noteId),
  parent_task_app_id: text(t.parentTaskId),
  work: obj(t.work),
  ai_verification: t.aiVerification ?? null,
  escalated: t.escalated ?? null,
  created_by: fk(t.createdBy),
  created_by_app_id: text(t.createdBy),
  completed_at: text(t.completedAt),
  created_at: at(t.createdAt),
});

/* Brainstorming sessions. Nested inside a project today, so invisible unless
   you open that one project. */
export const momRow = (m, projectId) => ({
  app_id: text(m.id),
  project_id: text(projectId),
  title: text(m.title),
  at: at(m.at || m.createdAt),
  body: text(m.body || m.text || m.summary),
  attendees: arr(m.attendees),
  decisions: arr(m.decisions),
  created_by: text(m.by || m.createdBy),
  created_at: at(m.createdAt || m.at),
});

export const projectChatRow = (c, projectId) => ({
  app_id: text(c.id),
  project_id: text(projectId),
  at: at(c.at || c.createdAt),
  who: text(c.who),
  author: text(c.author || c.name),
  text: text(c.text),
  meta: obj(c.meta),
});

export const projectIntelRow = (i, projectId) => ({
  app_id: text(i.id),
  project_id: text(projectId),
  at: at(i.at || i.createdAt),
  kind: text(i.kind || i.type),
  title: text(i.title),
  body: text(i.body || i.text),
  payload: obj(i.payload),
});

export const assistantLogRow = (m) => ({
  app_id: text(m.id),
  date: date(m.date),
  at: at(m.at || m.createdAt),
  who: text(m.who),
  author: text(m.author || m.name),
  text: text(m.text),
  ok: typeof m.ok === "boolean" ? m.ok : null,
  meta: obj(m.meta),
});

export const kpiRow = (k) => ({
  app_id: text(k.id),
  pm_id: fk(k.pmId),
  pm_app_id: text(k.pmId),
  date: date(k.date),
  type: text(k.type),
  at: at(k.at),
});

export const workUpdateRow = (w) => ({
  app_id: text(w.id),
  user_id: fk(w.userId),
  user_app_id: text(w.userId),
  date: date(w.date),
  note: text(w.note),
  score: num(w.score),
  feedback: text(w.feedback),
  kpi_hits: arr(w.kpiHits),
  created_at: at(w.createdAt),
});

export const trainingRow = (t) => ({
  app_id: text(t.id),
  user_id: fk(t.userId),
  user_app_id: text(t.userId),
  title: String(t.title || "").trim() || "(untitled)",
  resource: text(t.resource),
  due: date(t.due),
  status: text(t.status) || "Assigned",
  assigned_by: fk(t.assignedBy),
  assigned_by_app_id: text(t.assignedBy),
  created_at: at(t.createdAt),
});

export const memoryRow = (m) => ({
  app_id: text(m.id),
  type: text(m.type) || "note",
  title: text(m.title),
  content: text(m.content),
  created_by: text(m.createdBy),
  created_at: at(m.createdAt),
  // `embedding` is left alone. schema.sql already gives this table a
  // vector(1536) column and an ivfflat index; nothing computes embeddings yet,
  // so writing null here would be wrong — the column is simply not mentioned.
});

export const syncLogRow = (s) => ({
  app_id: text(s.id),
  target: text(s.target),
  detail: text(s.detail),
  at: at(s.at),
});

/* ── the mirror ───────────────────────────────────────────────────────────── */

const quoted = (v) => `"${String(v).replace(/"/g, '""')}"`;

/* Upsert `rows` into `table` on `key`, then delete anything in the table that
   is no longer present. Never throws. */
async function mirror(sb, table, rows, key) {
  const seen = new Set();
  const unique = rows.filter((r) => {
    const k = r[key];
    if (!k || seen.has(k)) return false;
    seen.add(k);
    return true;
  });

  if (unique.length) {
    const { error } = await sb.from(table).upsert(unique, { onConflict: key });
    if (error) throw new Error(`${table}: ${error.message}`);
  }

  // PostgREST has no "delete where not in (empty list)", so the two cases are
  // written separately rather than building a filter that matches nothing.
  const del = unique.length
    ? sb.from(table).delete().not(key, "in", `(${unique.map((r) => quoted(r[key])).join(",")})`)
    : sb.from(table).delete().not(key, "is", null);
  const { error } = await del;
  if (error) throw new Error(`${table}: ${error.message}`);

  return unique.length;
}

/* Mirror the whole workspace. `state` is the same object the blob is built
   from, plus the pieces nested inside projects.

   Returns { ok, wrote: {table: n}, errors: [] } and never throws — the caller
   is a save path that must not be interrupted by a backend hiccup. A failure
   in one table does not stop the others. */
export async function syncAll(sb, state = {}) {
  const out = { ok: true, wrote: {}, errors: [] };
  if (!sb) return { ok: false, wrote: {}, errors: ["no client"] };

  const projects = arr(state.projects).filter((p) => p && String(p.projectId || "").trim());

  // The three collections that live *inside* each project, flattened out so
  // they can be asked about across the whole company.
  const moms = [], chat = [], intel = [];
  for (const p of projects) {
    const pid = String(p.projectId).trim();
    for (const m of arr(p.moms)) moms.push(momRow(m, pid));
    for (const c of arr(p.chat)) chat.push(projectChatRow(c, pid));
    for (const i of arr(p.intelligence)) intel.push(projectIntelRow(i, pid));
  }

  const jobs = [
    ["projects", projects.map(projectRow), "project_id"],
    ["clients", arr(state.clients).map(clientRow), "app_id"],
    ["scrum_notes", arr(state.notes).map(scrumNoteRow), "app_id"],
    ["tasks", arr(state.tasks).map(taskRow), "app_id"],
    ["moms", moms, "app_id"],
    ["project_chat", chat, "app_id"],
    ["project_intel", intel, "app_id"],
    ["assistant_log", arr(state.assistantLog).map(assistantLogRow), "app_id"],
    ["kpi_log", arr(state.kpiLog).map(kpiRow), "app_id"],
    ["work_updates", arr(state.workUpdates).map(workUpdateRow), "app_id"],
    ["trainings", arr(state.trainings).map(trainingRow), "app_id"],
    ["memory", arr(state.memory).map(memoryRow), "app_id"],
    ["drive_sync_log", arr(state.syncLog).map(syncLogRow), "app_id"],
  ];

  for (const [table, rows, key] of jobs) {
    try {
      out.wrote[table] = await mirror(sb, table, rows, key);
    } catch (e) {
      out.ok = false;
      out.errors.push(e?.message || String(e));
    }
  }
  return out;
}

/* Kept for the projects-only path and for tests. */
export async function syncProjects(sb, projects) {
  if (!sb) return { ok: false, wrote: 0, removed: 0, error: "no client" };
  try {
    const wrote = await mirror(sb, "projects", arr(projects)
      .filter((p) => p && String(p.projectId || "").trim())
      .map(projectRow), "project_id");
    return { ok: true, wrote, removed: 0, error: "" };
  } catch (e) {
    return { ok: false, wrote: 0, removed: 0, error: e?.message || String(e) };
  }
}
