import { tbl, tableName, ensureLayout, usingLegacyLayout } from "./tables.js";

/* ─── REAL ROWS, ALONGSIDE THE BLOB ──────────────────────────────────────────
   App.jsx persists the whole workspace as two JSON strings in `pms.workspace`.
   That is
   fine for the app's own reads, but nothing else can ask a question of it: no
   "which projects are overdue", no join to an invoice, no per-row permissions,
   and — because it is one row — no way to hide anything from anyone.

   So every save also mirrors the workspace out to the real tables, one row per
   thing. The blob stays authoritative; this is a one-way mirror:

     App state ──► pms.workspace blob (authoritative, unchanged)
               └─► core.projects, core.orgs, pms.scrum_notes, pms.tasks,
                   pms.meetings + its ideas / decisions / challenges,
                   messages (project chat AND the assistant, one table),
                   project_intel, kpi_log, work_updates, trainings,
                   memory, drive_sync_log      (a queryable copy)

   Nothing reads these rows back yet, which is exactly why it is safe to turn
   on: a failed write is invisible to the app and the next save repairs it.

   Run, in order:
       supabase/projects-into-a-real-table.sql
       supabase/every-table-filled.sql
       supabase/nested-data-into-tables.sql
   Without them each write fails harmlessly and the tables stay empty.

   ── Two shape rules worth knowing ──
   • `app_id` is the app's own short id (`uid()`, 8 chars). It is the upsert
     key on every table, because the app's ids are not uuids and the uuid
     primary keys are generated by Postgres.
   • Columns declared `uuid references profiles(id)` only ever receive a real
     uuid. The seeded roster uses ids like 'u-admin', which would violate the
     foreign key and fail the entire batch, so those travel in the matching
     `*_app_id` text column instead.                                          */

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const isUuid = (v) => typeof v === "string" && UUID_RE.test(v);
/* Only a real uuid may enter a uuid column. */
const fk = (v) => (isUuid(v) ? v : null);

/* An empty date input is "", which Postgres rejects for a `date` column. */
const date = (v) => (typeof v === "string" && /^\d{4}-\d{2}-\d{2}$/.test(v) ? v : null);
const text = (v) => (v == null || v === "" ? null : String(v));
const at = (v) => text(v) || new Date().toISOString();
const arr = (v) => (Array.isArray(v) ? v : []);
const obj = (v) => (v && typeof v === "object" && !Array.isArray(v) ? v : {});
/* Number(null), Number(""), Number(false) and Number([]) are all 0, so a
   plain Number() check turns "no score" into a real zero. When Claude is
   unreachable the app stores score: null and shows "unscored" — recording 0
   would manufacture a damning performance record out of a backend outage. */
/* Build a real instant from a UTC day + a local clock time. */
const localToIso = (day, hm) => {
  if (!date(day) || !/^\d{2}:\d{2}$/.test(String(hm || ""))) return null;
  const [h, mi] = String(hm).split(":").map(Number);
  const d = new Date(`${day}T00:00:00`);      // local midnight of that day
  d.setHours(h, mi, 0, 0);
  return Number.isNaN(d.getTime()) ? null : d.toISOString();
};
const num = (v) => (v === null || v === undefined || v === "" || typeof v === "boolean" || Array.isArray(v)
  || !Number.isFinite(Number(v)) ? null : Number(v));
/* Integer columns reject 3.5. A model asked for 1-5 sometimes answers 3.5. */
const int = (v) => { const n = num(v); return n === null ? null : Math.round(n); };

/* ── row builders ─────────────────────────────────────────────────────────── */

export function projectRow(p) {
  return {
    project_id: String(p.projectId || "").trim(),
    app_id: text(p.id),
    id_mode: text(p.idMode) || "auto",
    // The assistant path stamps `source`, the form stamps `origin`.
    origin: text(p.origin ?? p.source),
    name: String(p.name || "").trim() || String(p.projectId || ""),
    // The wizard writes `desc`; only the assistant path ever writes
    // `description`. Reading one name silently produced null for every
    // project created through the UI.
    description: text(p.desc ?? p.description),
    client_name: text(p.clientName),
    client_id: text(p.clientId),
    industry: text(p.industry),
    org_size: text(p.orgSize),
    contact: obj(p.contact),
    start_date: date(p.startDate),
    deadline: date(p.deadline),
    status: text(p.status) || "Planning",
    linked_ids: arr(p.linkedIds).filter(Boolean).map(String),
    team: arr(p.team),
    known_status: text(p.knownStatus),
    // Derived exactly as the app derives it, so `where sanctioned` works.
    sanctioned: (text(p.status) || "Planning") !== "Planning",
    drive_learning: text(p.driveLearning),
    lld_customer: p.lldCustomer ?? null,
    lld_designer: p.lldDesigner ?? null,
    // One object per project, not a list, so it lives on the project itself.
    drive_analysis: text(p.driveAnalysis?.text),
    drive_analysis_at: text(p.driveAnalysis?.at),
    drive_analysis_live: typeof p.driveAnalysis?.live === "boolean" ? p.driveAnalysis.live : null,
    // One plan per project, so its own fields sit on the project; its stages
    // become rows (see stageRows).
    plan_summary: text(p.plan?.summary),
    plan_updated_at: text(p.plan?.updatedAt),
    plan_source: text(p.plan?.source),
    plan_log: arr(p.plan?.log),
    created_by: fk(p.createdBy),
    created_at: at(p.createdAt),
  };
}

export const clientRow = (c) => ({
  app_id: text(c.id),
  client_id: text(c.clientId),
  name: String(c.name || "").trim() || "(unnamed)",
  industry: text(c.industry),
  org_size: text(c.orgSize),
});

/* The daily scrum. One row per note, so "what did we say on the 7th" is a
   query rather than a scan of a JSON string. */
export const scrumNoteRow = (n) => ({
  app_id: text(n.id),
  date: date(n.date),
  note_no: int(n.noteNo),
  time: text(n.time),
  raw: text(n.raw),
  organized: n.organized ?? null,
  origin: text(n.origin) || "manual",
  // The one column the reorganisation renamed: `by` became `author_id`.
  // Send whichever this database actually has, or the whole batch bounces.
  ...(usingLegacyLayout()
    ? { by: fk(n.by), by_app_id: text(n.by) }
    : { author_id: fk(n.by), author_app_id: text(n.by) }),
  project_id: text(n.projectId),
  created_at: at(n.createdAt),
});

export const taskRow = (t) => ({
  app_id: text(t.id),
  project_id: text(t.projectId),
  linked: t.linked !== false,
  title: String(t.title || "").trim() || "(untitled)",
  assignee_id: fk(t.assigneeId),
  assignee_app_id: text(t.assigneeId),
  // The app writes `assigneeName`; `assignee` is only ever a transient field
  // injected for stage matching. Reading the wrong one meant this column was
  // always null.
  assignee_name: text(t.assigneeName ?? t.assignee),
  date: date(t.date),
  start_time: text(t.startTime),
  end_time: text(t.endTime),
  steps: arr(t.steps),
  conditions: arr(t.conditions),
  // The column has a CHECK; an unknown status would fail the whole batch.
  status: ["pending", "in-progress", "blocked", "done"].includes(t.status) ? t.status : "pending",
  origin: text(t.origin) || "scrum",
  stage_id: text(t.stageId),
  note_app_id: text(t.noteId),
  parent_task_app_id: text(t.parentTaskId),
  mom_app_id: text(t.momId),
  work: obj(t.work),
  ai_verification: t.aiVerification ?? null,
  escalated: t.escalated ?? null,
  // None of these appear in any task constructor — they are written by later
  // partial updates as work progresses, which is how they were missed.
  started_at: text(t.startedAt),
  steps_done: arr(t.stepsDone),
  block_note: text(t.blockNote),
  last_feedback: text(t.lastFeedback),
  created_by: fk(t.createdBy),
  created_by_app_id: text(t.createdBy),
  completed_at: text(t.completedAt),
  created_at: at(t.createdAt),
});

/* Brainstorming sessions. Nested inside a project today, so a decision taken
   on 1752 is invisible unless you open 1752 and scroll.

   The app's shape is { id, date, time, by, byName, attendees, raw, ai, at,
   title, savedTo }, where `attendees` is a free-text string the user typed and
   `ai` holds the analysis. The whole `ai` object is kept verbatim so nothing is
   lost if its shape changes; the three lists worth querying across sessions
   are also flattened into child rows below. */
export const momRow = (m, projectId) => ({
  app_id: text(m.id),
  project_id: text(projectId),
  date: date(m.date),
  time: text(m.time),
  at: at(m.at),
  by_app_id: text(m.by),
  by_id: fk(m.by),
  by_name: text(m.byName),
  attendees: text(m.attendees),
  title: text(m.title),
  raw: String(m.raw || ""),
  summary: text(m.ai?.summary),
  saved_to: text(m.savedTo),
  ai: m.ai ?? null,
  created_at: at(m.at),
});

/* `actions` and `lessons` are deliberately absent: the app already turns them
   into rows in `tasks` and `memory`, so copying them here would give two
   answers to one question. */
export const momIdeaRows = (m) => arr(m.ai?.ideas).map((i, seq) => ({
  seq,
  by_name: text(i.by),
  idea: text(i.idea),
  impact: text(i.impact),
  value: int(i.value),
  why: text(i.why),
}));

export const momDecisionRows = (m) => arr(m.ai?.decisions).map((d, seq) => ({
  seq, what: text(d.what), owner: text(d.owner),
}));

export const momChallengeRows = (m) => arr(m.ai?.challenges).map((c, seq) => ({
  seq, problem: text(c.problem), status: text(c.status), solution: text(c.solution),
}));

/* Project chat and the assistant transcript are the same record, differing
   only in whether a project is named. One table, one query, one place to
   embed from later. */
export const projectMessageRow = (c, projectId) => ({
  app_id: text(c.id),
  scope: "project",
  project_id: text(projectId),
  day: date(String(c.at || "").slice(0, 10)),
  at: at(c.at),
  time: text(c.time),
  who: text(c.who) || "me",
  by_app_id: text(c.by),
  by_id: fk(c.by),
  by_name: text(c.byName),
  text: text(c.text),
  ok: typeof c.ok === "boolean" ? c.ok : null,
  files: arr(c.files),
  docs: arr(c.docs),
  doc: c.doc ?? null,
});

export const assistantMessageRow = (m) => ({
  app_id: text(m.id),
  scope: "assistant",
  project_id: null,
  day: date(m.date),
  // `date` is a UTC day but `time` is local wall-clock (App.jsx todayStr /
  // nowHM), so concatenating them with a literal Z was wrong by the whole UTC
  // offset — 5.5 hours in IST. Assistant and project messages share one table
  // and are ordered by `at`, so that mis-stamp interleaved them wrongly.
  at: at(m.at || localToIso(m.date, m.time)),
  time: text(m.time),
  who: text(m.who) || "me",
  by_app_id: text(m.by),
  by_id: fk(m.by),
  by_name: text(m.byName),
  text: text(m.text),
  ok: typeof m.ok === "boolean" ? m.ok : null,
  files: arr(m.files),
  docs: arr(m.docs),
  // who === 'doc' messages carry the document the assistant produced.
  doc: m.doc ?? null,
});

/* A note someone wrote, plus the AI-tidied version. Both are kept — `raw` is
   what a person actually said, and that is the version worth embedding. */
export const projectIntelRow = (i, projectId) => ({
  app_id: text(i.id),
  project_id: text(projectId),
  at: at(i.at),
  by_app_id: text(i.by),
  by_id: fk(i.by),
  raw: text(i.raw),
  text: text(i.text),
});

export const kpiRow = (k) => ({
  app_id: text(k.id),
  pm_id: fk(k.pmId),
  pm_app_id: text(k.pmId),
  date: date(k.date),
  type: text(k.type),
  at: at(k.at),
});

export const workUpdateRow = (w) => ({
  app_id: text(w.id),
  user_id: fk(w.userId),
  user_app_id: text(w.userId),
  date: date(w.date),
  note: text(w.note),
  score: int(w.score),
  feedback: text(w.feedback),
  kpi_hits: arr(w.kpiHits),
  // The app stamps `at`, never `createdAt`.
  at: text(w.at),
  created_at: at(w.at || w.createdAt),
});

export const trainingRow = (t) => ({
  app_id: text(t.id),
  user_id: fk(t.userId),
  user_app_id: text(t.userId),
  title: String(t.title || "").trim() || "(untitled)",
  resource: text(t.resource),
  due: date(t.due),
  status: text(t.status) || "Assigned",
  assigned_by: fk(t.assignedBy),
  assigned_by_app_id: text(t.assignedBy),
  at: text(t.at),
  created_at: at(t.at || t.createdAt),
});

export const memoryRow = (m) => ({
  app_id: text(m.id),
  type: text(m.type) || "note",
  title: text(m.title),
  content: text(m.content),
  file_name: text(m.fileName),
  created_by: text(m.createdBy),
  created_at: at(m.createdAt),
  updated_at: text(m.updatedAt),
  // `embedding` is left alone. schema.sql already gives this table a
  // vector(1536) column and an ivfflat index; nothing computes embeddings yet,
  // so writing null here would be wrong — the column is simply not mentioned.
});

export const syncLogRow = (s) => ({
  app_id: text(s.id),
  target: text(s.target),
  detail: text(s.detail),
  at: at(s.at),
});

/* The stages a project's plan is broken into — and what every task's
   `stage_id` actually points at. Without these rows that column is a dangling
   reference: you can group by 'design' but nothing tells you its name, its
   order, its owner or whether it is done.

   `start` and `end` are renamed on the way out; `end` is a reserved word. */
export const stageRows = (p) => arr(p.plan?.stages)
  .filter((st) => st && st.id)
  .map((st, seq) => ({
    app_id: `${p.projectId}:${st.id}`,
    project_id: String(p.projectId),
    stage_id: String(st.id),
    seq,
    name: text(st.name),
    status: text(st.status),
    track: text(st.track),
    start_on: date(st.start),
    end_on: date(st.end),
    owner_name: text(st.owner),
    note: text(st.note),
    evidence: arr(st.evidence),
  }));

/* Who is on a project. Also held as jsonb on `projects.team`, which is what
   the app reads; these rows are the joinable form, so "what is Jerom on" is a
   query rather than a scan of every project's jsonb. Keyed '<project>:<slot>'
   because a person occupies one slot per project. */
export const teamRows = (p) => arr(p.team)
  .filter((r) => r && r.userId)
  .map((r) => ({
    app_id: `${p.projectId}:${r.slot}`,
    project_app_id: text(p.id),
    project_id: null,          // uuid FK; the app's project id is not a uuid
    user_app_id: text(r.userId),
    user_id: fk(r.userId),
    slot: String(r.slot || ""),
  }));

/* ── the mirror ───────────────────────────────────────────────────────────── */

/* PostgREST parses a quoted list element with BACKSLASH escapes, not doubled
   quotes. Getting this wrong is not cosmetic: a value ending in a backslash
   escapes its own closing quote and swallows the rest of the list. */
const quoted = (v) => `"${String(v).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

/* What this browser wrote last time, per table. The prune below deletes only
   keys that WE wrote and have since removed — never "everything that is not
   in my copy".

   That distinction is the whole safety story:

   • On the first save after a reload this is empty, so nothing is deleted. A
     boot that silently came up on seed data — which happens when the blob read
     returns no rows rather than an error — can no longer wipe the database.
   • "Reset to seed data" is a local action again, not one that destroys the
     shared mirror for the whole company.
   • Two people with the app open no longer delete each other's rows on every
     save. Each prunes only what it personally removed.
   • The delete filter now lists only the removed keys, not every surviving
     one, so it cannot outgrow the URL length limit at ~1,000 rows.

   The trade is stale rows: a deletion made in another browser is not mirrored
   until this one also sees it. Stale beats destroyed. */
const lastWrote = new Map();

const DELETE_CHUNK = 100;

/* Upsert `rows` into `table`, then delete only the keys this browser wrote
   before and no longer has. Never throws for a reason the caller can ignore. */
async function mirror(sb, table, rows, key) {
  const seen = new Set();
  const unique = rows.filter((r) => {
    const k = r[key];
    if (!k || seen.has(k)) return false;
    seen.add(k);
    return true;
  });

  if (unique.length) {
    const { error } = await tbl(sb, table).upsert(unique, { onConflict: key });
    if (error) throw new Error(`${tableName(table)}: ${error.message}`);
  }

  const before = lastWrote.get(table);
  const gone = before ? [...before].filter((k) => !seen.has(k)) : [];
  for (let i = 0; i < gone.length; i += DELETE_CHUNK) {
    const batch = gone.slice(i, i + DELETE_CHUNK);
    const { error } = await tbl(sb, table).delete()
      .in(key, batch);
    if (error) throw new Error(`${tableName(table)}: ${error.message}`);
  }
  // Only recorded once the writes have actually landed, so a failed save does
  // not make us forget rows we are still responsible for.
  lastWrote.set(table, seen);

  return unique.length;
}

/* Mirror the whole workspace. `state` is the same object the blob is built
   from, plus the pieces nested inside projects.

   Returns { ok, wrote: {table: n}, errors: [] } and never throws — the caller
   is a save path that must not be interrupted by a backend hiccup. A failure
   in one table does not stop the others. */
export async function syncAll(sb, state = {}) {
  // Decide once which layout this database is in; every job then goes there.
  await ensureLayout(sb);
  const out = { ok: true, wrote: {}, errors: [] };
  if (!sb) return { ok: false, wrote: {}, errors: ["no client"] };

  const projects = arr(state.projects).filter((p) => p && String(p.projectId || "").trim());

  // The three collections that live *inside* each project, flattened out so
  // they can be asked about across the whole company. A brainstorming session
  // additionally fans out into its own child rows.
  const moms = [], ideas = [], decisions = [], challenges = [], messages = [], intel = [];
  for (const p of projects) {
    const pid = String(p.projectId).trim();
    for (const m of arr(p.moms)) {
      if (!m?.id) continue;
      moms.push(momRow(m, pid));
      // '<mom>:<seq>' is the child key — see nested-data-into-tables.sql. It is
      // what lets the children use the same upsert-and-prune path as every
      // other table instead of a bespoke one.
      for (const r of momIdeaRows(m))      ideas.push({ app_id: `${m.id}:${r.seq}`, mom_app_id: m.id, ...r });
      for (const r of momDecisionRows(m))  decisions.push({ app_id: `${m.id}:${r.seq}`, mom_app_id: m.id, ...r });
      for (const r of momChallengeRows(m)) challenges.push({ app_id: `${m.id}:${r.seq}`, mom_app_id: m.id, ...r });
    }
    for (const c of arr(p.chat)) messages.push(projectMessageRow(c, pid));
    for (const i of arr(p.intelligence)) intel.push(projectIntelRow(i, pid));
  }
  for (const m of arr(state.assistantLog)) messages.push(assistantMessageRow(m));

  // Logical names, resolved to schema + table by src/lib/tables.js.
  const jobs = [
    ["projects", projects.map(projectRow), "project_id"],
    ["assignments", projects.flatMap(teamRows), "app_id"],
    ["stages", projects.flatMap(stageRows), "app_id"],
    ["orgs", arr(state.clients).map(clientRow), "app_id"],
    ["scrum_notes", arr(state.notes).map(scrumNoteRow), "app_id"],
    ["tasks", arr(state.tasks).map(taskRow), "app_id"],
    // meetings before its children, so the foreign key has something to point at.
    ["meetings", moms, "app_id"],
    ["meeting_ideas", ideas, "app_id"],
    ["meeting_decisions", decisions, "app_id"],
    ["meeting_challenges", challenges, "app_id"],
    ["messages", messages, "app_id"],
    ["intel", intel, "app_id"],
    ["kpi_log", arr(state.kpiLog).map(kpiRow), "app_id"],
    ["work_updates", arr(state.workUpdates).map(workUpdateRow), "app_id"],
    ["trainings", arr(state.trainings).map(trainingRow), "app_id"],
    ["memory", arr(state.memory).map(memoryRow), "app_id"],
    ["sync_log", arr(state.syncLog).map(syncLogRow), "app_id"],
  ];

  for (const [table, rows, key] of jobs) {
    try {
      out.wrote[table] = await mirror(sb, table, rows, key);
    } catch (e) {
      out.ok = false;
      out.errors.push(e?.message || String(e));
    }
  }
  return out;
}

/* Kept for the projects-only path and for tests. */
export async function syncProjects(sb, projects) {
  if (!sb) return { ok: false, wrote: 0, removed: 0, error: "no client" };
  try {
    const wrote = await mirror(sb, "projects", arr(projects)
      .filter((p) => p && String(p.projectId || "").trim())
      .map(projectRow), "project_id");
    return { ok: true, wrote, removed: 0, error: "" };
  } catch (e) {
    return { ok: false, wrote: 0, removed: 0, error: e?.message || String(e) };
  }
}
